/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TButton: typeof import('tdesign-vue-next')['Button']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TInput: typeof import('tdesign-vue-next')['Input']
    TMessage: typeof import('tdesign-vue-next')['Message']
    TPopconfirm: typeof import('tdesign-vue-next')['Popconfirm']
    TTextarea: typeof import('tdesign-vue-next')['Textarea']
  }
}
